<?xml version="1.0"?>
<package format="3">
  <name>controller_node</name>
  <version>0.1.0</version>
  <description>Pure Pursuit path follower for Ackermann-steered base.</description>
  <maintainer email="rajeevreddy1009@gmail.com">Rajeev Reddy</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>ackermann_msgs</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
